create table if not exists public.private_access_probe (
  id bigint generated by default as identity primary key,
  note text not null default 'server-only verification',
  created_at timestamptz not null default now()
);

alter table public.private_access_probe enable row level security;

revoke all on table public.private_access_probe from anon, authenticated;
revoke all on sequence public.private_access_probe_id_seq from anon, authenticated;

grant all on table public.private_access_probe to service_role;
grant usage, select on sequence public.private_access_probe_id_seq to service_role;

comment on table public.private_access_probe is
  'Temporary table for verifying that browser roles are denied and server-only access works.';
